<?php
// Auto-generated by Alfa (MVC refactor)
define('DB_DRIVER', 'mysql');
define('DB_HOST', 'localhost');
define('DB_NAME', 'database');
define('DB_USER', 'root');
define('DB_PASS', '');
define('APP_ROOT', dirname(__DIR__));
define('BASE_PATH', dirname(APP_ROOT));
define('VIEW_PATH', APP_ROOT . '/views');
